version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: petclinic-db
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="root" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    ports:
      - "3001:3306"
    volumes:
      - db-volume:/var/lib/mysql  

  spring_app:
    image: my-petclinic
    container_name: petclinic-app
    ports:
      - "3002:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_PROFILES_ACTIVE=mysql
    restart: always   
  
volumes:
  db-volume:
